### ISSUE TITLE
mkdir: cannot create directory cbt: File exists

### ISSUE THREAD

**Issue by gpetrucce** [GoogleCloudPlatform/PerfKitBenchmarker#4226]
I'm getting an error when the benchmark tries to download GO.

![image](https://user-images.githubusercontent.com/106392811/236335606-d80fa9f4-3f23-44ac-a51a-d537c239fa23.png)

Then starts a loop when tries to run the following command:

throughput.yaml] 2023-05-04 21:37:17,206 e0d312f5 Thread-125 cloud_bigtable_ycsb(1/1) INFO     Retrying exception running Install: Got non-zero return code (1) executing cd /opt/pkb && mkdir cbt
[throughput.yaml] Full command: ssh -A -p 22 perfkit@34.66.35.49 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=30 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /tmp/perfkitbenchmarker/runs/e0d312f5/perfkitbenchmarker_keyfile cd /opt/pkb && mkdir cbt
[throughput.yaml] STDOUT: STDERR: Warning: Permanently added '34.66.35.49' (ECDSA) to the list of known hosts.
[throughput.yaml] mkdir: cannot create directory cbt: File exists

**Comment by s-deitz** [comment]
Please share the PKB log or command.

**Comment by dlott** [comment]
Has this been fixed with https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/commit/6cd8ac2ce9c7fb812d11bd3a81d8891a1f9f3bb3

**Comment by georgecma** [comment]
I'm running `sudo docker run --init --rm -v ~/pkb_configs:/pkb/configs -v /tmp:/tmp gcr.io/cloud-bigtable-ecosystem/pkb:latest` but the error is still there.

**Comment by liujiongxin** [comment]
Ok, we can update the docker image to pick up the fix.

**Comment by georgecma** [comment]
Latest image has been updated, this issue can be closed.

**Comment by dlott** [comment]
Closing per above.
