### ISSUE TITLE
Benchmarks keep on failing - problem with python scripts

### ISSUE THREAD

**Issue by Eldainorn** [GoogleCloudPlatform/PerfKitBenchmarker#919]
For the last few days I've been trying to get PerfkitBenchmarker working with Azure and AWS. I followed all the instructions that are provided here and on the official website. I have successfully installed everything needed, also got the accounts for Azure and AWS. The problem arises when I am trying to benchmark anything, i.e. while executing 
 `./pkb.py --cloud=Azure --benchmark=iperf ...`

Everytime I execute a benchmark my tests are failing while calling certain Python functions like (see attached pictures):
- PrepareVm() - I get an error stating: Exception occurred while calling PrepareVM(...)
- DeleteVm(), same thing
Another error that I am getting during the execution of iperf test is simply: Error during benchmark iperf.

Then, when the test finishes I get that the benchmark iperf failed, success rate is 0.0%. I also tried different test, same issue. And same issue for Azure and AWS.

I am using Python 2.7.3, Azure client 0.9.9, latest Perfkit (1.3.0).

If anyone knows what might be wrong I would very much appreciate it. I really need to get this working somehow.

I also attached images of the error. It follows from top to bottom, showing the execution of iperf test.

![error perfkit1](https://cloud.githubusercontent.com/assets/10331828/14113044/8b1c33d0-f5d1-11e5-9bff-7f775020c429.png)
![error perfkit2](https://cloud.githubusercontent.com/assets/10331828/14113045/8b1e8e8c-f5d1-11e5-8ab2-83720413588e.png)
![error perfkit3](https://cloud.githubusercontent.com/assets/10331828/14113047/8b232604-f5d1-11e5-8282-3b0a5ea184d9.png)
![error perfkit4](https://cloud.githubusercontent.com/assets/10331828/14113046/8b225224-f5d1-11e5-8b22-b8fe92289b29.png)

**Comment by noahl** [comment]
Hi @Eldainorn , your PKB command line looks good. As far as I can tell from your screenshots, the last PKB function in the stack trace for prepare-phase errors is always `_GetDefaultImagesFromAzure()`. Is that correct? (I would guess that the errors in `DeleteVm()` are because `PrepareVM()` didn't manage to create a VM, so they will go away once we fix the prepare step.)

Could you please run `azure vm image list --json` at your command prompt and paste the results here? That's the command that PKB is running that it can't interpret the output of. Thanks!

**Comment by voellm** [comment]
It looks like you are hitting and Azure quota issue.

Have you been able to create a VM with using the azure command like the following?

azure vm create --vm-size=Medium pkb-44ed3a3a-0 b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_4-LTS-amd64-server-20160314-en-us-30GB  --location='West US' --userName voellm

happy to help debug more...

**Comment by Eldainorn** [comment]
Thank you for such a quick answer.

@noahl `_GetDefaultImagesFromAzure()` is indeed the last function, as we can see from the images I provided. I also think that you are right that `DeleteVm()` is failing because `PrepareVm()` failes beforehand.

I ran the `azure vm image list --json` command and what I find weird is that I do not get complete output. I checked if there are some other options for printing the output but it seems that there none that would help me (only verbose option). Here is the output I get (it's quite a lot):

[
  {
    "category": "Public",
    "label": "CoreCLR x64 Beta5 (11624) with PartsUnlimited Demo App on Ubuntu Server 14.04 LTS",
    "location": "Southeast Asia;Australia East;Australia Southeast;North Europe;West Europe;Japan East;Japan West;Central US;East US;South Central US",
    "logicalSizeInGB": 30,
    "name": "03f55de797f546a1b29d1b8d66be687a__CoreCLR-x64-Beta5-Linux-PartsUnlimited-Demo-App-201504.29",
    "operatingSystemType": "Linux",
    "eula": "http://go.microsoft.com/fwlink/?LinkId=521895",
    "description": "Linux VM image with coreclr-x64-beta5-11624 installed to /opt/dnx. This image is based on Ubuntu 14.04 LTS, with prerequisites of CoreCLR installed. It also contains PartsUnlimited demo app which runs on the installed coreclr. The demo app is installed to /opt/demo. To run the demo, please type the command '/opt/demo/Kestrel' in a terminal window. The website is listening on port 5004. Please enable or map a endpoint of HTTP port 5004 for your azure VM.",
    "imageFamily": "CoreCLR x64 Beta5 (11624) with PartsUnlimited Demo App on Ubuntu Server 14.04 LTS",
    "publishedDate": "2015-04-29T07:00:00.000Z",
    "isPremium": false,
    "privacyUri": "http://go.microsoft.com/fwlink/?LinkID=528096",
    "recommendedVMSize": "Standard_D1",
    "publisherName": "Microsoft Visual Studio Group",
    "iconUri": "Ubuntu-cof-45.png",
    "smallIconUri": "Ubuntu-cof-45.png",
    "iOType": "Standard_LRS"
  },
  {
    "category": "Public",
    "label": "Team Foundation Server 2013 Update 4 on Windows Server 2012 R2",
    "location": "Southeast Asia;Australia East;Australia Southeast;North Europe;West Europe;Japan East;Japan West;Central US;East US;South Central US",
    "logicalSizeInGB": 128,
    "name": "03f55de797f546a1b29d1b8d66be687a__Team-Foundation-Server-2013-Update4-WS2012R2",
    "operatingSystemType": "Windows",
    "eula": "http://www.microsoft.com/en-us/download/details.aspx?id=13350",
    "description": "Microsoft Team Foundation Server 2013 Trial on Windows Server 2012 R2 Update. Virtual Machines created with this trial image will require a product key for Team Foundation Server (such as from an MSDN Subscription). This image includes a complete installation of Team Foundation Server 2013 Update 4. Some components require additional setup and configuration. You can configure SQL Server using SQL Server Express included in this image, by downloading and installing SQL Server Standard edition (from an MSDN Subscription), or by connect to a pre-existing SQL Server. Minimum virtual machine size for this image is Medium. For more details on TFS server setup please see the [Team Foundation Server install guide|http://msdn.microsoft.com/en-us/library/dd631902.aspx].",
    "imageFamily": "Team Foundation Server 2013 Update 4 on Windows Server 2012 R2",
    "publishedDate": "2014-11-12T08:00:00.000Z",
    "isPremium": false,
    "privacyUri": "http://go.microsoft.com/fwlink/?LinkID=286720",
    "recommendedVMSize": "Medium",
    "publisherName": "Microsoft Visual Studio Group",
    "iconUri": "VisualStudio2013_100.png",
    "smallIconUri": "VisualStudio2013_45.png",
    "iOType": "Standard_LRS"
  },
  {
    "category": "Public",
    "label": "Team Foundation Server 2013 Update 4 on Windows Server 2012 R2",
    "location": "Southeast Asia;Australia East;Australia Southeast;North Europe;West Europe;Japan East;Japan West;Central US;East US;South Central US",
    "logicalSizeInGB": 128,
    "name": "03f55de797f546a1b29d1b8d66be687a__Team-Foundation-Server-2013-Update4-WS2012R2-201503.20",
    "operatingSystemType": "Windows",
    "eula": "http://www.microsoft.com/en-us/download/details.aspx?id=13350",
    "description": "Microsoft Team Foundation Server 2013 Trial on Windows Server 2012 R2 Update. Virtual Machines created with this trial image will require a product key for Team Foundation Server (such as from an MSDN Subscription). This image includes a complete installation of Team Foundation Server 2013 Update 4. Some components require additional setup and configuration. You can configure SQL Server using SQL Server Express included in this image, by downloading and installing SQL Server Standard edition (from an MSDN Subscription), or by connect to a pre-existing SQL Server. Minimum virtual machine size for this image is Medium. For more details on TFS server setup please see the [Team Foundation Server install guide|http://msdn.microsoft.com/en-us/library/dd631902.aspx].",
    "imageFamily": "Team Foundation Server 2013 Update 4 on Windows Server 2012 R2",
    "publishedDate": "2015-03-20T07:00:00.000Z",
    "isPremium": false,
    "privacyUri": "http://go.microsoft.com/fwlink/?LinkID=286720",
    "recommendedVMSize": "Medium",
    "publisherName": "Microsoft Visual Studio Group",
    "iconUri": "VisualStudio2013_100.png",
    "smallIconUri": "VisualStudio2013_45.png",
    "iOType": "Standard_LRS"
  },
  {
    "category": "Public",
    "label": "Team Foundation Server 2013 Update 4 on Windows Server 2012 R2",
    "location": "Southeast Asia;Australia East;Australia Southeast;North Europe;West Europe;Japan East;Japan West;Central US;East US;South Central US",
    "logicalSizeInGB": 128,
    "name": "03f55de797f546a1b29d1b8d66be687a__Team-Foundation-Server-2013-Update4-WS2012R2-201503.27",
    "operatingSystemType": "Windows",
    "eula": "http://www.microsoft.com/en-us/legal/IntellectualProperty/UseTerms/Default.aspx",
    "description": "Microsoft Team Foundation Server 2013 Trial on Windows Server 2012 R2 Update. Virtual Machines created with this trial image will require a product key for Team Foundation Server (such as from an MSDN Subscription). This image includes a complete installation of Team Foundation Server 2013 Update 4. Some components require additional setup and configuration. You can configure SQL Server using SQL Server Express included in this image, by downloading and installing SQL Server Standard edition (from an MSDN Subscription), or by connect to a pre-existing SQL Server. Minimum virtual machine size for this image is Medium. For more details on TFS server setup please see the [Team Foundation Server install guide|http://msdn.microsoft.com/en-us/library/dd631902.aspx].",
    "imageFamily": "Team Foundation Server 2013 Update 4 on Windows Server 2012 R2",
    "publishedDate": "2015-03-27T07:00:00.000Z",
    "isPremium": false,
    "privacyUri": "http://go.microsoft.com/fwlink/?LinkID=286720",
    "recommendedVMSize": "Medium",
    "publisherName": "Microsoft Visual Studio Group",
    "iconUri": "VisualStudio2013_100.png",
    "smallIconUri": "VisualStudio2013_45.png",
    "iOType": "Standard_LRS"
  },
  {
    "category": "Public",
    "label": "Visual Studio Community 2013 Update 5 with Azure 2.8 on Windows Server 2012 R2",
    "location": "Southeast Asia;Australia East;Australia Southeast;North Europe;West Europe;Central India;South India;West India;Japan East;Japan West;Central US;East US;South Central US",
    "logicalSizeInGB": 128,
    "name": "03f55de797f546a1b29d1b8d66be687a__VS-2013-Comm-VSU5-AzureSDK-2.8-WS2012R2",
    "operatingSystemType": "Windows",
    "eula": "http://go.microsoft.com/fwlink/?LinkID=430755",
    "description": "This image of Visual Studio Community 2013 Update 5 with Azure Tools 2.8 enables you to unleash the full power of Visual Studio to develop cross-platform solutions.  Create apps in one unified IDE, and incorporate new languages, features, and development tools into them with Visual Studio Extensions (available in the Visual Studio Gallery).",
    "imageFamily": "Visual Studio Community 2013 Update 5 with Azure 2.8 on Windows Server 2012 R2",
    "publishedDate": "2016-01-05T08:00:00.000Z",
    "isPremium": false,
    "privacyUri": "http://go.microsoft.com/fwlink/?LinkID=286720",
    "recommendedVMSize": "Standard_D2",
    "publisherName": "Microsoft Visual Studio Group",
    "iconUri": "VisualStudio2013_100.png",
    "smallIconUri": "VisualStudio2013_45.png",
    "iOType": "Standard_LRS"
  },
  {
    "category": "Public",
    "label": "Visual Studio Community 2013 Update 5 with Azure 2.8 on Windows Server 2012 R2",
    "location": "Southeast Asia;Australia East;Australia Southeast;North Europe;West Europe;Central India;South India;West India;Japan East;Japan West;Central US;East US;South Central US",
    "logicalSizeInGB": 128,
    "name": "03f55de797f546a1b29d1b8d66be687a__VS-2013-Comm-VSU5-AzureSDK-28-WS2012R22016-03-03",
    "operatingSystemType": "Windows",
    "eula": "http://go.microsoft.com/fwlink/?LinkId=430755",
    "description": "This image of Visual Studio Community 2013 Update 5 with Azure Tools 2.8 enables you to unleash the full power of Visual Studio to develop cross-platform solutions.  Create apps in one unified IDE, and incorporate new languages, features, and development tools into them with Visual Studio Extensions (available in the Visual Studio Gallery).",
    "imageFamily": "Visual Studio Community 2013 Update 5 with Azure 2.8 on Windows Server 2012 R2",
    "publishedDate": "2016-03-03T08:00:00.000Z",
    "isPremium": false,
    "privacyUri": "http://go.microsoft.com/fwlink/?LinkId=286720",
    "recommendedVMSize": "Standard_D2",
    "publisherName": "Microsoft Visual Studio Group",
    "iconUri": "VisualStudio2013_100.png",
    "smallIconUri": "VisualStudio2013_45.png",
    "iOType": "Standard_LRS"
  },
  {
    "category": "Public",
    "label": "Visual Studio Community 2013 Update 5 with Tools for Apache Cordova CTP 3.2 on Windows Server 2012 R2",
    "location": "Southeast Asia;Australia East;Australia Southeast;North Europe;West Europe;Central India;South India;West India;Japan East;Japan West;Central US;East US;South Central US",
    "logicalSizeInGB": 128,
    "name": "03f55de797f546a1b29d1b8d66be687a__VS-2013-Comm-VSU5-Cordova-CTP3.2-AzureSDK-2.8-WS2012R2",
    "operatingSystemType": "Windows",
    "eula": "http://go.microsoft.com/fwlink/?LinkID=430755",
    "description": "This image provides Visual Studio Community 2013 Update 5, Azure Tools 2.8, and CTP 3.2 of the Tools for Apache Cordova running on Windows Server 2012 R2.  It allows you to easily and quickly set up a development environment in Azure to build and test Android, iOS, and Windows apps using HTML, CSS, and JavaScript. Please see [http://go.microsoft.com/fwlink/?LinkID=397716|http://go.microsoft.com/fwlink/?LinkID=397716] for more information.",
    "imageFamily": "Visual Studio Community 2013 Update 5 with Tools for Apache Cordova CTP 3.2 on Windows Server 2012 R2",
    "publishedDate": "2016-01-15T08:00:00.000Z",
    "isPremium": false,
    "privacyUri": "http://go.microsoft.com/fwlink/?LinkId=286720",
    "recommendedVMSize": "Medium",
    "publisherName": "Microsoft Visual Studio Group",
    "iconUri": "VisualStudio2013_100.png",
    "smallIconUri": "VisualStudio2013_45.png",
    "iOType": "Standard_LRS"
  },
  {
    "category": "Public",
    "label": "Visual Studio Premium 2013 Update 5 on Windows Server 2012",
    "location": "Southeast Asia;Australia East;Australia Southeast;North Europe;West Europe;Central India;South India;West India;Japan East;Japan West;Central US;East US;South Central US",
    "logicalSizeInGB": 128,
    "name": "03f55de797f546a1b29d1b8d66be687a__VS-2013-Prem-VSU5-AzureSDK-2.8-WS2012R2-2",
    "operatingSystemType": "Windows",
    "eula": "http://msdn.microsoft.com/subscriptions/eula",
    "description": "The Visual Studio Premium 2013 Update 5 developer desktop is an offering exclusive to MSDN subscribers. The image includes Visual Studio Premium 2013 Update 5, SharePoint 2013 Trial, SQL Server 2012 Developer edition and configuration scripts to quickly create a development environment for Web, SQL and SharePoint 2013 development. To learn how to configure any development environment you can follow the links on the desktop. We recommend a Standard_D2 VM size for SQL and Web development and Standard_D3 VM size for SharePoint development. Please see [http://go.microsoft.com/fwlink/?LinkID=329862|http://go.microsoft.com/fwlink/?LinkID=329862] for a detailed description of the image. Privacy note: This image has been preconfigured for Microsoft Azure, including enabling the Visual Studio Experience Improvement Program for Visual Studio, which can be disabled.",
    "imageFamily": "Visual Studio Premium 2013 Update 5 on Windows Server 2012",
    "publishedDate": "2016-01-29T08:00:00.000Z",
    "isPremium": false,
    "privacyUri": "http://go.microsoft.com/fwlink/?LinkID=286720",
    "recommendedVMSize": "Standard_D2",
    "publisherName": "Microsoft Visual Studio Group",
    "iOType": "Standard_LRS"
  },
  {
    "category": "Public",
    "label": "Visual Studio Ultimate 2013 Update 5 on Windows Server 2012",
    "location": "Southeast Asia;Australia East;Australia Southeast;North Europe;West Europe;Central India;South India;West India;Japan East;Japan West;Central US;East US;South Central US",
    "logicalSizeInGB": 128,
    "name": "03f55de797f546a1b29d1b8d66be687a__VS-2013-Ultimate-VSU5-AzureSDK-2.8-WS2012R2-2",
    "operatingSystemType": "Windows",
    "eula": "http://msdn.microsoft.com/subscriptions/eula",
    "description": "The Visual Studio Ultimate 2013 Update 5 developer desktop is an offering exclusive to MSDN subscribers. The image includes Visual Studio Ultimate 2013 Update 5, SharePoint 2013 Trial, SQL Server 2012 Developer edition and configuration scripts to quickly create a development environment for Web, SQL and SharePoint 2013 development. To learn how to configure any development environment you can follow the links on the desktop. We recommend a Standard_D2 VM size for SQL and Web development and Standard A4 VM size for SharePoint development. Please see [http://go.microsoft.com/fwlink/?LinkID=329862|http://go.microsoft.com/fwlink/?LinkID=329862] for a detailed description of the image. Privacy note: This image has been preconfigured for Microsoft Azure, including enabling the Visual Studio Experience Improvement Program for Visual Studio, which can be disabled.",
    "imageFamily": "Visual Studio Ultimate 2013 Update 5 on Windows Server 2012",
    "publishedDate": "2016-01-29T08:00:00.000Z",
    "isPremium": false,
    "privacyUri": "http://go.microsoft.com/fwlink/?LinkID=286720",
    "recommendedVMSize": "Standard_D2",
    "publisherName": "Microsoft Visual Studio Group",
    "iOType": "Standard_LRS"
  },
  {
    "category": "Public",
    "label": "Visual Studio Community 2015 with Azure SDK 2.8 on Windows Server 2012 R2",
    "location": "Southeast Asia;Australia East;Australia Southeast;North Europe;West Europe;Central India;South India;West India;Japan

@voellm 
I tried the command you provided but it doesn't work for me. Here is what I get:
![errorcloudcreate](https://cloud.githubusercontent.com/assets/10331828/14116777/cb55baec-f5e1-11e5-8211-e796419e1254.png)

I then changed the location to `--location="East US"`  and then I got different error that stated: `error: The specified DNS name is already taken` and at the end command failed.

I asked my friend to try to run the tests for AWS and he managed to get it to work without any problems. Maybe I'll try to reinstall everything (Python, pip, PerfKit, clients, ...). Could there be incompatibility between different versions of PerfKit/Python/... ?

**Comment by hildrum** [comment]
@Eldainorn 
I ran into this recently--with my Azure account, I'm not able to create VMs in `West US`, but I can in `East US`.  

That is, when I do:
`azure vm create --location='West US' testname 6a83c2d016534a7a917bcd21b6e1c0c9__Debian-9-DAILY-amd64-20160318.0  --userName=test`
I get the same error you get above.   On the other hand, the following command runs successfully:
`azure vm create --location='East US' hildrum-test 6a83c2d016534a7a917bcd21b6e1c0c9__Debian-9-DAILY-amd64-20160318.0  --userName=test`

Try:
`./pkb.py --benchmarks=iperf --cloud=Azure --zone='East US'`

**Comment by skschneider** [comment]
Truncated `azure vm image list --json` looks like a dup of #860, which should have been fixed by #878. Give me a little while to check if that's in the version of PKB you're using.

**Comment by skschneider** [comment]
Looks like #878 is not in v1.3.0. This issue is already fixed in master and will presumably be in v1.4.0. You might be able to get around the specific failing command by explicitly picking an image via the `--image` flag, but your current environment may truncate the stdout and stderr of other commands. I recommend checking out a copy of the master branch.

**Comment by Eldainorn** [comment]
@hildrum, @skschneider  I am still getting the same problem. Thx anyways. It seems that there is some problem with the Azure. My friend could run the tests for AWS and DigitalOcean but he also got the same problems as I did when he was running tests for the Azure. I will try it with the Benchmarker 1.4.0 when it releases. Or we will just change the platform if the problems persist.

**Comment by skschneider** [comment]
v1.4.0 has been released. Any update on this issue?

**Comment by Eldainorn** [comment]
Unfortunately I already deleted my trial account for Azure. We had to proceed with testing so we picked Google Cloude Platform over Azure.

Only thing I can comment further is that I tried with the v1.2.0 and I had the same problem as with the v1.3.0.

**Comment by skschneider** [comment]
Sorry we weren't faster. Considering the similarity of this issue to #860, I'm quite confident that the fix in v1.4.0 has addressed this. Since there's nothing further planned, I'm closing this issue for now, but if you ever see this error again, we can resume investigating.
